backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"

i18n:
  structure: single_file # Cambiar a single_file para colecciones de tipo files
  locales:
    - en
    - es

collections:
  # Colección para las páginas individuales (Home, Who We Are, Contact, etc.)
  - name: "pages"
    label: "Pages"
    i18n: true # Habilitamos i18n para la colección
    files:
      - name: "home"
        label: "Home Page"
        file: "content/home.md"
        i18n: true
        fields:
          # HERO SECTION
          - { label: "Word 1", name: "word1", widget: "string", i18n: true }
          - { label: "Word 2", name: "word2", widget: "string", i18n: true }
          - { label: "Word 3", name: "word3", widget: "string", i18n: true }
          - {
              label: "Subtitle Part1",
              name: "subtitlePart1",
              widget: "markdown",
              i18n: true,
            }
          - {
              label: "Subtitle Part2",
              name: "subtitlePart2",
              widget: "markdown",
              i18n: true,
            }
          - { label: "CTA Text", name: "ctaText", widget: "string", i18n: true }
          - {
              label: "CTA Video Text",
              name: "ctaVideoText",
              widget: "string",
              i18n: true,
            }
          # WHO WE ARE
          - {
              label: "Who We Are Title",
              name: "whoWeAreTitle",
              widget: "markdown",
              i18n: true,
            }
          - {
              label: "Who We Are Subtitle",
              name: "whoWeAreSubtitle",
              widget: "markdown",
              i18n: true,
            }
          - {
              label: "Who We Are Paragraph",
              name: "whoWeAreParagraph",
              widget: "markdown",
              i18n: true,
            }
          - {
              label: "Who We Are Button Text",
              name: "whoWeAreButtonText",
              widget: "string",
              i18n: true,
            }
          # OUR CLIENTS (Separa imagen y nombre por idioma)
          - label: "Clients for Dark Mode"
            name: "clientsDark"
            widget: "list"
            max: 7
            fields:
              - { label: "Client Name", name: "clientName", widget: "string" }
              - { label: "Client Image", name: "clientImage", widget: "image" }

          - label: "Clients for Light Mode"
            name: "clientsLight"
            widget: "list"
            max: 7
            fields:
              - { label: "Client Name", name: "clientName", widget: "string" }
              - { label: "Client Image", name: "clientImage", widget: "image" }
          # CALL TO ACTION (CTA)
          - {
              label: "Our clients CTA Title",
              name: "ctaTitle",
              widget: "markdown",
              i18n: true,
            }
          - {
              label: "Our clients CTA Button Text",
              name: "ctaButtonText",
              widget: "string",
              i18n: true,
            }

      - name: "who_we_are"
        label: "Who We Are Page"
        file: "content/who_we_are.md"
        i18n: true
        fields:
          # HERO SECTION
          - {
              label: "Hero Title",
              name: "heroTitle",
              widget: "markdown",
              i18n: true,
            }
          - {
              label: "Hero Subtitle",
              name: "heroSubtitle",
              widget: "markdown",
              i18n: true,
            }
          - {
              label: "Hero Button Text",
              name: "heroButtonText",
              widget: "string",
              i18n: true,
            }
          # STORY
          - {
              label: "Story Title",
              name: "storyTitle",
              widget: "markdown",
              i18n: true,
            }
          - {
              label: "Story Subtitle",
              name: "storySubtitle",
              widget: "markdown",
              i18n: true,
            }
          - {
              label: "Story Paragraph 1",
              name: "storyParagraph1",
              widget: "text",
              i18n: true,
            }
          - {
              label: "Story Paragraph 2",
              name: "storyParagraph2",
              widget: "text",
              i18n: true,
            }
            # STORY
            - {
                label: "Story Title",
                name: "storyTitle",
                widget: "markdown",
                i18n: true,
              }
            - {
                label: "Story Subtitle",
                name: "storySubtitle",
                widget: "markdown",
                i18n: true,
              }
          # TEAM MEMBERS (Nombre compartido, rol en ambos idiomas)
          - label: "Team Members"
            name: "teamMembers"
            widget: "list"
            i18n: false # El nombre no necesita traducción
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Full Name", name: "fullName", widget: "string" }
              - {
                  label: "Role",
                  name: "role",
                  widget: "object",
                  i18n: true, # El rol se traduce
                  fields:
                    [
                      { label: "Role (English)", name: "en", widget: "string" },
                      { label: "Role (Spanish)", name: "es", widget: "string" },
                    ],
                }
              - { label: "Photo", name: "photo", widget: "image" }
              - { label: "Video", name: "video", widget: "file" }

      - name: "contact"
        label: "Contact Page"
        file: "content/contact.md"
        i18n: true
        fields:
          - {
              label: "Contact Title",
              name: "contactTitle",
              widget: "markdown",
              i18n: true,
            }
          - {
              label: "Contact Subtitle",
              name: "contactSubtitle",
              widget: "markdown",
              i18n: true,
            }
          - label: "Form"
            name: "form"
            widget: "object"
            i18n: true
            fields:
              - { label: "Full Name", name: "fullName", widget: "string" }
              - { label: "Email", name: "email", widget: "string" }
              - { label: "Phone Number", name: "phoneNumber", widget: "string" }
              - { label: "Company Name", name: "companyName", widget: "string" }
              - {
                  label: "Services You Are Looking For",
                  name: "services",
                  widget: "list",
                  field:
                    { label: "Service", name: "service", widget: "string" },
                }
              - {
                  label: "Budget",
                  name: "budget",
                  widget: "list",
                  field:
                    {
                      label: "Budget Option",
                      name: "budgetOption",
                      widget: "string",
                    },
                }
              - {
                  label: "Project Details",
                  name: "projectDetails",
                  widget: "text",
                }
              - {
                  label: "Form Button Text",
                  name: "formButtonText",
                  widget: "string",
                  i18n: true,
                }

  # Colección para Secciones Compartidas
  - name: "shared"
    label: "Shared Sections"
    i18n: true
    files:
      # Misión (Mission Section)
      - name: "mission"
        label: "Mission Section"
        file: "content/mission.md"
        i18n: true
        fields:
          - {
              label: "Mission Title",
              name: "missionTitle",
              widget: "markdown",
              i18n: true,
            }
          - {
              label: "Mission Subtitle",
              name: "missionSubtitle",
              widget: "markdown",
              i18n: true,
            }
          - {
              label: "Third Title",
              name: "thirdTitle",
              widget: "markdown",
              i18n: true,
            }
          - {
              label: "Background Photo",
              name: "backgroundPhoto",
              widget: "image",
            }

      # Testimonials Section
      - name: "testimonials"
        label: "Testimonials Section"
        file: "content/testimonials.md"
        i18n: true
        fields:
          - {
              label: "Testimonials Title",
              name: "testimonialsTitle",
              widget: "markdown",
              i18n: true,
            }
          - {
              label: "Testimonials Subtitle",
              name: "testimonialsSubtitle",
              widget: "markdown",
              i18n: true,
            }
          - label: "Testimonials"
            name: "testimonials"
            widget: "list"
            i18n: true
            fields:
              - {
                  label: "Testimonial Image",
                  name: "testimonialImage",
                  widget: "image",
                }
              - {
                  label: "Testimonial Name",
                  name: "testimonialName",
                  widget: "string",
                }
              - {
                  label: "Testimonial Role",
                  name: "testimonialRole",
                  widget: "string",
                  i18n: true,
                }
              - {
                  label: "Testimonial Text",
                  name: "testimonialText",
                  widget: "text",
                  i18n: true,
                }

      # Main CTA Section
      - name: "main_cta"
        label: "Main CTA Section"
        file: "content/main_cta.md"
        i18n: true
        fields:
          - {
              label: "CTA Title",
              name: "ctaTitle",
              widget: "markdown",
              i18n: true,
            }
          - {
              label: "CTA Subtitle",
              name: "ctaSubtitle",
              widget: "markdown",
              i18n: true,
            }
          - {
              label: "CTA Button Text",
              name: "ctaButtonText",
              widget: "string",
              i18n: true,
            }

      # Free Session CTA
      - name: "free_session_cta"
        label: "Free Session CTA"
        file: "content/free_session_cta.md"
        i18n: true
        fields:
          - { label: "Avatar Photo", name: "avatarPhoto", widget: "image" }
          - { label: "Title", name: "title", widget: "markdown", i18n: true }
          - {
              label: "Subtitle",
              name: "subtitle",
              widget: "string",
              i18n: true,
            }
          - {
              label: "Button Text",
              name: "buttonText",
              widget: "string",
              i18n: true,
            }
          - { label: "Button Link", name: "buttonLink", widget: "string" }

  # Colección General para Header y Footer
  - name: "general"
    label: "General"
    i18n: true
    files:
      # Header Configuration
      - name: "header"
        label: "Header"
        file: "content/header.md"
        i18n: false # Social Links no requieren traducción
        fields:
          - {
              label: "Header Button Text",
              name: "headerButtonText",
              widget: "string",
              i18n: true,
            }
          - {
              label: "Header Social Links",
              name: "socialLinks",
              widget: "object",
              fields:
                [
                  { label: "Instagram", name: "instagram", widget: "string" },
                  { label: "Facebook", name: "facebook", widget: "string" },
                  { label: "TikTok", name: "tiktok", widget: "string" },
                  { label: "YouTube", name: "youtube", widget: "string" },
                  { label: "Pinterest", name: "pinterest", widget: "string" },
                  { label: "LinkedIn", name: "linkedin", widget: "string" },
                ],
            }

      # Footer Configuration
      - name: "footer"
        label: "Footer"
        file: "content/footer.md"
        fields:
          - {
              label: "Developer Signature",
              name: "developerSignature",
              widget: "string",
              i18n: true,
            }

      # Video Compartido (General)
      - name: "video"
        label: "Video"
        file: "content/video.md"
        i18n: false # El video no requiere traducción
        fields:
          - { label: "Upload Video", name: "videoUrl", widget: "file" }
          - { label: "Full Video", name: "fullVideo", widget: "string" }
