backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "pages" # Nombre de la colección
    label: "Pages" # Etiqueta que se muestra en el CMS
    folder: "content/pages" # Carpeta donde se almacenarán los archivos de esta colección
    create: true # Permite a los usuarios crear nuevos ítems en esta colección
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Formato del nombre de archivo
    fields: # Define los campos que los ítems tendrán
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
