backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    create: true
    delete: false
    files:
      - name: "home_en"
        label: "Home Page (English)"
        file: "content/home_en.md"
        fields:
          - { label: "Word 1", name: "word1", widget: "string" }
          - { label: "Word 2", name: "word2", widget: "string" }
          - { label: "Word 3", name: "word3", widget: "string" }
          - { label: "Subtitle Part1", name: "subtitlePart1", widget: "string" }
          - { label: "Subtitle Part2", name: "subtitlePart2", widget: "string" }
          - { label: "CTA Text", name: "ctaText", widget: "string" }
          - { label: "CTA Video Text", name: "ctaVideoText", widget: "string" }
          - { label: "Upload Video", name: "videoUrl", widget: "file" } # Campo para subir video
          - {
              label: "Full Video",
              name: "fullVideo",
              widget: "string",
              hint: "URL of the full YouTube video",
            } # URL del video completo
          # WHO WE ARE Section
          - {
              label: "Who We Are Title",
              name: "whoWeAreTitle",
              widget: "string",
            }
          - {
              label: "Who We Are Subtitle",
              name: "whoWeAreSubtitle",
              widget: "markdown",
            } # Rich text for spans with class styles
          - {
              label: "Who We Are Paragraph",
              name: "whoWeAreParagraph",
              widget: "markdown",
            } # Rich text for spans with class styles
          - {
              label: "Who We Are Button Text",
              name: "whoWeAreButtonText",
              widget: "string",
            }
          # WHAT WE DO Section
          - {
              label: "What We Do Title",
              name: "whatWeDoTitle",
              widget: "string",
            }
          - {
              label: "What We Do Subtitle",
              name: "whatWeDoSubtitle",
              widget: "markdown",
            } # Rich text
          - {
              label: "What We Do Paragraph",
              name: "whatWeDoParagraph",
              widget: "text",
            }
          - {
              label: "What We Do Button Text",
              name: "whatWeDoButtonText",
              widget: "string",
            }
          # OUR CLIENTS Section
          - {
              label: "Our Clients Title",
              name: "ourClientsTitle",
              widget: "string",
            }
          - {
              label: "Our Clients Subtitle",
              name: "ourClientsSubtitle",
              widget: "markdown",
            } # Rich text
          - label: "Clients"
            name: "clients"
            widget: "list"
            fields:
              - { label: "Client Image", name: "clientImage", widget: "image" }
              - { label: "Client Name", name: "clientName", widget: "string" }
          - { label: "CTA Title", name: "ctaTitle", widget: "markdown" } # Rich text
          - {
              label: "CTA Button Text",
              name: "ctaButtonText",
              widget: "string",
            }

      - name: "shared"
        label: "Shared Sections"
        file: "content/shared.md"
        fields:
          # SERVICIOS Section
          - { label: "Services Title", name: "servicesTitle", widget: "string" }
          - {
              label: "Services Description",
              name: "servicesDescription",
              widget: "text",
            }
          - label: "Subservices"
            name: "subservices"
            widget: "list"
            fields:
              - { label: "Subservice", name: "subservice", widget: "string" }
              - {
                  label: "Service Image",
                  name: "serviceImage",
                  widget: "image",
                }
          # OUR MISSION Section
          - { label: "Mission Title", name: "missionTitle", widget: "string" }
          - {
              label: "Mission Subtitle",
              name: "missionSubtitle",
              widget: "markdown",
            } # Rich text
          - { label: "Third Title", name: "thirdTitle", widget: "string" } # Can be renamed
          - {
              label: "Background Photo",
              name: "backgroundPhoto",
              widget: "image",
            }
          # TESTIMONIALS Section
          - {
              label: "Testimonials Title",
              name: "testimonialsTitle",
              widget: "string",
            }
          - {
              label: "Testimonials Subtitle",
              name: "testimonialsSubtitle",
              widget: "markdown",
            } # Rich text
          - label: "Testimonials"
            name: "testimonials"
            widget: "list"
            fields:
              - {
                  label: "Testimonial Image",
                  name: "testimonialImage",
                  widget: "image",
                }
              - {
                  label: "Testimonial Name",
                  name: "testimonialName",
                  widget: "string",
                }
              - {
                  label: "Testimonial Role",
                  name: "testimonialRole",
                  widget: "string",
                }
              - {
                  label: "Testimonial Text",
                  name: "testimonialText",
                  widget: "text",
                }
          # MAIN CTA Section
          - { label: "Main CTA Title", name: "mainCtaTitle", widget: "string" }
          - {
              label: "Main CTA Subtitle",
              name: "mainCtaSubtitle",
              widget: "markdown",
            } # Rich text
          - {
              label: "Main CTA Button Text",
              name: "mainCtaButtonText",
              widget: "string",
            }
          # FREE SESSION Section
          - { label: "Avatar Photo", name: "avatarPhoto", widget: "image" }
          - {
              label: "Free Session Title",
              name: "freeSessionTitle",
              widget: "markdown",
            } # Rich text
          - {
              label: "Free Session Subtitle",
              name: "freeSessionSubtitle",
              widget: "string",
            }
          - {
              label: "Free Session Button Text",
              name: "freeSessionButtonText",
              widget: "string",
            }
          - {
              label: "Free Session Button Link",
              name: "freeSessionButtonLink",
              widget: "string",
            }

      - name: "about"
        label: "Who We Are Page"
        file: "content/about.md"
        fields:
          # HERO SECTION
          - { label: "Hero Title", name: "heroTitle", widget: "string" }
          - { label: "Hero Subtitle", name: "heroSubtitle", widget: "markdown" } # Rich text
          - {
              label: "Hero Button Text",
              name: "heroButtonText",
              widget: "string",
            }
          # STORY Section
          - { label: "Story Title", name: "storyTitle", widget: "markdown" } # Rich text
          - {
              label: "Story Subtitle",
              name: "storySubtitle",
              widget: "markdown",
            } # Rich text
          - {
              label: "Story Paragraph 1",
              name: "storyParagraph1",
              widget: "text",
            }
          - {
              label: "Story Paragraph 2",
              name: "storyParagraph2",
              widget: "text",
            }
          # TEAM Section
          - { label: "Team Title", name: "teamTitle", widget: "markdown" } # Rich text
          - { label: "Team Subtitle", name: "teamSubtitle", widget: "markdown" } # Rich text
          - {
              label: "Team Description",
              name: "teamDescription",
              widget: "text",
            }
          - label: "Team Members"
            name: "teamMembers"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Full Name", name: "fullName", widget: "string" }
              - { label: "Role", name: "role", widget: "string" }
              - { label: "Photo", name: "photo", widget: "image" }
              - { label: "Video", name: "video", widget: "string" }
          - {
              label: "Team CTA Title",
              name: "teamCtaTitle",
              widget: "markdown",
            } # Rich text
          - {
              label: "Team CTA Button Text",
              name: "teamCtaButtonText",
              widget: "string",
            }
          - {
              label: "Team CTA Button Link",
              name: "teamCtaButtonLink",
              widget: "string",
            }
          # GALLERY TEAM Section
          - { label: "Gallery Photo 1", name: "galleryPhoto1", widget: "image" }
          - { label: "Gallery Photo 2", name: "galleryPhoto2", widget: "image" }
          - { label: "Gallery Photo 3", name: "galleryPhoto3", widget: "image" }

      - name: "services"
        label: "What We Do Page"
        file: "content/services.md"
        fields:
          # HERO SECTION
          - { label: "Hero Title", name: "heroTitle", widget: "string" }
          - { label: "Hero Subtitle", name: "heroSubtitle", widget: "string" }
          - {
              label: "Hero Button Text",
              name: "heroButtonText",
              widget: "string",
            }

      - name: "contact"
        label: "Contact Page"
        file: "content/contact.md"
        fields:
          # HEADER AND FORM
          - { label: "Contact Title", name: "contactTitle", widget: "markdown" } # Rich text
          - {
              label: "Contact Subtitle",
              name: "contactSubtitle",
              widget: "string",
            }
          - label: "Form"
            name: "form"
            widget: "object"
            fields:
              - { label: "Full Name", name: "fullName", widget: "string" }
              - { label: "Email", name: "email", widget: "string" }
              - { label: "Phone Number", name: "phoneNumber", widget: "string" }
              - { label: "Company Name", name: "companyName", widget: "string" }
              - {
                  label: "Services You Are Looking For",
                  name: "services",
                  widget: "list",
                  field:
                    { label: "Service", name: "service", widget: "string" },
                } # Dynamic options
              - {
                  label: "Budget",
                  name: "budget",
                  widget: "list",
                  field:
                    {
                      label: "Budget Option",
                      name: "budgetOption",
                      widget: "string",
                    },
                } # Dynamic options
              - {
                  label: "Project Details",
                  name: "projectDetails",
                  widget: "text",
                }
              - {
                  label: "Form Button Text",
                  name: "formButtonText",
                  widget: "string",
                }

      - name: "navigation"
        label: "Navigation"
        file: "content/navigation.md"
        fields:
          - {
              label: "Header Button Text",
              name: "headerButtonText",
              widget: "string",
            }
          - label: "Pages"
            name: "pages"
            widget: "list"
            fields:
              - { label: "Page Title", name: "pageTitle", widget: "string" }
              - { label: "Page Link", name: "pageLink", widget: "string" }

      - name: "footer"
        label: "Footer"
        file: "content/footer.md"
        fields:
          - {
              label: "Developer Signature",
              name: "developerSignature",
              widget: "string",
            }
