backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    create: true
    delete: false
    files:
      - name: "home_en"
        label: "Home Page (English)"
        file: "content/home_en.md"
        fields:
          - { label: "Word 1", name: "word1", widget: "string" }
          - { label: "Word 2", name: "word2", widget: "string" }
          - { label: "Word 3", name: "word3", widget: "string" }
          - { label: "Subtitle Part1", name: "subtitlePart1", widget: "string" }
          - { label: "Subtitle Part2", name: "subtitlePart2", widget: "string" }
          - { label: "CTA Text", name: "ctaText", widget: "string" }
          - { label: "CTA Video Text", name: "ctaVideoText", widget: "string" }
          - { label: "Upload Video", name: "videoUrl", widget: "file" } # Campo para subir video
      - name: "home_es"
        label: "Home Page (Spanish)"
        file: "content/home_es.md"
        fields:
          - { label: "Palabra 1", name: "word1", widget: "string" }
          - { label: "Palabra 2", name: "word2", widget: "string" }
          - { label: "Palabra 3", name: "word3", widget: "string" }
          - {
              label: "Subtítulo Parte 1",
              name: "subtitlePart1",
              widget: "string",
            }
          - {
              label: "Subtítulo Parte 2",
              name: "subtitlePart2",
              widget: "string",
            }
          - { label: "Texto del CTA", name: "ctaText", widget: "string" }
          - {
              label: "Texto del Video CTA",
              name: "ctaVideoText",
              widget: "string",
            }
          - { label: "Subir Video", name: "videoUrl", widget: "file" } # Campo para subir video
