backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    create: true
    delete: false
    files:
      - name: "home_en"
        label: "Home Page (English)"
        file: "content/home_en.md"
        fields:
          - { label: "Word 1", name: "word1", widget: "string" }
          - { label: "Word 2", name: "word2", widget: "string" }
          - { label: "Word 3", name: "word3", widget: "string" }
          - { label: "Subtitle Part1", name: "subtitlePart1", widget: "string" }
          - { label: "Subtitle Part2", name: "subtitlePart2", widget: "string" }
          - { label: "CTA Text", name: "ctaText", widget: "string" }
          - { label: "CTA Video Text", name: "ctaVideoText", widget: "string" }
          - { label: "Upload Video", name: "videoUrl", widget: "file" }
          - {
              label: "Full Video",
              name: "fullVideo",
              widget: "string",
              hint: "URL of the full YouTube video",
            }
          - {
              label: "Who We Are Title",
              name: "whoWeAreTitle",
              widget: "string",
            }
          - {
              label: "Who We Are Subtitle",
              name: "whoWeAreSubtitle",
              widget: "markdown",
            }
          - {
              label: "Who We Are Paragraph",
              name: "whoWeAreParagraph",
              widget: "markdown",
            }
          - {
              label: "Who We Are Button Text",
              name: "whoWeAreButtonText",
              widget: "string",
            }
          - {
              label: "What We Do Title",
              name: "whatWeDoTitle",
              widget: "string",
            }
          - {
              label: "What We Do Subtitle",
              name: "whatWeDoSubtitle",
              widget: "markdown",
            }
          - {
              label: "What We Do Paragraph",
              name: "whatWeDoParagraph",
              widget: "text",
            }
          - {
              label: "What We Do Button Text",
              name: "whatWeDoButtonText",
              widget: "string",
            }
          - {
              label: "Our Clients Title",
              name: "ourClientsTitle",
              widget: "string",
            }
          - {
              label: "Our Clients Subtitle",
              name: "ourClientsSubtitle",
              widget: "markdown",
            }
          - label: "Clients"
            name: "clients"
            widget: "list"
            fields:
              - { label: "Client Image", name: "clientImage", widget: "image" }
              - { label: "Client Name", name: "clientName", widget: "string" }
          - { label: "CTA Title", name: "ctaTitle", widget: "markdown" }
          - {
              label: "CTA Button Text",
              name: "ctaButtonText",
              widget: "string",
            }

      - name: "home_es"
        label: "Home Page (Spanish)"
        file: "content/home_es.md"
        fields:
          - { label: "Palabra 1", name: "word1", widget: "string" }
          - { label: "Palabra 2", name: "word2", widget: "string" }
          - { label: "Palabra 3", name: "word3", widget: "string" }
          - {
              label: "Subtítulo Parte 1",
              name: "subtitlePart1",
              widget: "string",
            }
          - {
              label: "Subtítulo Parte 2",
              name: "subtitlePart2",
              widget: "string",
            }
          - { label: "Texto del CTA", name: "ctaText", widget: "string" }
          - {
              label: "Texto del Video CTA",
              name: "ctaVideoText",
              widget: "string",
            }
          - { label: "Subir Video", name: "videoUrl", widget: "file" }
          - {
              label: "Video Completo",
              name: "fullVideo",
              widget: "string",
              hint: "URL del video completo en YouTube",
            }
          - {
              label: "Título ¿Quiénes Somos?",
              name: "whoWeAreTitle",
              widget: "string",
            }
          - {
              label: "Subtítulo ¿Quiénes Somos?",
              name: "whoWeAreSubtitle",
              widget: "markdown",
            }
          - {
              label: "Párrafo ¿Quiénes Somos?",
              name: "whoWeAreParagraph",
              widget: "markdown",
            }
          - {
              label: "Texto del Botón ¿Quiénes Somos?",
              name: "whoWeAreButtonText",
              widget: "string",
            }
          - {
              label: "Título ¿Qué Hacemos?",
              name: "whatWeDoTitle",
              widget: "string",
            }
          - {
              label: "Subtítulo ¿Qué Hacemos?",
              name: "whatWeDoSubtitle",
              widget: "markdown",
            }
          - {
              label: "Descripción ¿Qué Hacemos?",
              name: "whatWeDoParagraph",
              widget: "text",
            }
          - {
              label: "Texto del Botón ¿Qué Hacemos?",
              name: "whatWeDoButtonText",
              widget: "string",
            }
          - {
              label: "Título Nuestros Clientes",
              name: "ourClientsTitle",
              widget: "string",
            }
          - {
              label: "Subtítulo Nuestros Clientes",
              name: "ourClientsSubtitle",
              widget: "markdown",
            }
          - label: "Clientes"
            name: "clients"
            widget: "list"
            fields:
              - {
                  label: "Imagen del Cliente",
                  name: "clientImage",
                  widget: "image",
                }
              - {
                  label: "Nombre del Cliente",
                  name: "clientName",
                  widget: "string",
                }
          - { label: "Título CTA", name: "ctaTitle", widget: "markdown" }
          - {
              label: "Texto del Botón CTA",
              name: "ctaButtonText",
              widget: "string",
            }

      - name: "shared_en"
        label: "Shared Sections (English)"
        file: "content/shared_en.md"
        fields:
          - { label: "Services Title", name: "servicesTitle", widget: "string" }
          - {
              label: "Services Description",
              name: "servicesDescription",
              widget: "text",
            }
          - label: "Subservices"
            name: "subservices"
            widget: "list"
            fields:
              - { label: "Subservice", name: "subservice", widget: "string" }
              - {
                  label: "Service Image",
                  name: "serviceImage",
                  widget: "image",
                }
          - { label: "Mission Title", name: "missionTitle", widget: "string" }
          - {
              label: "Mission Subtitle",
              name: "missionSubtitle",
              widget: "markdown",
            }
          - { label: "Third Title", name: "thirdTitle", widget: "string" }
          - {
              label: "Background Photo",
              name: "backgroundPhoto",
              widget: "image",
            }
          - {
              label: "Testimonials Title",
              name: "testimonialsTitle",
              widget: "string",
            }
          - {
              label: "Testimonials Subtitle",
              name: "testimonialsSubtitle",
              widget: "markdown",
            }
          - label: "Testimonials"
            name: "testimonials"
            widget: "list"
            fields:
              - {
                  label: "Testimonial Image",
                  name: "testimonialImage",
                  widget: "image",
                }
              - {
                  label: "Testimonial Name",
                  name: "testimonialName",
                  widget: "string",
                }
              - {
                  label: "Testimonial Role",
                  name: "testimonialRole",
                  widget: "string",
                }
              - {
                  label: "Testimonial Text",
                  name: "testimonialText",
                  widget: "text",
                }
          - { label: "Main CTA Title", name: "mainCtaTitle", widget: "string" }
          - {
              label: "Main CTA Subtitle",
              name: "mainCtaSubtitle",
              widget: "markdown",
            }
          - {
              label: "Main CTA Button Text",
              name: "mainCtaButtonText",
              widget: "string",
            }
          - { label: "Avatar Photo", name: "avatarPhoto", widget: "image" }
          - {
              label: "Free Session Title",
              name: "freeSessionTitle",
              widget: "markdown",
            }
          - {
              label: "Free Session Subtitle",
              name: "freeSessionSubtitle",
              widget: "string",
            }
          - {
              label: "Free Session Button Text",
              name: "freeSessionButtonText",
              widget: "string",
            }
          - {
              label: "Free Session Button Link",
              name: "freeSessionButtonLink",
              widget: "string",
            }

      - name: "shared_es"
        label: "Shared Sections (Spanish)"
        file: "content/shared_es.md"
        fields:
          - {
              label: "Título Servicios",
              name: "servicesTitle",
              widget: "string",
            }
          - {
              label: "Descripción Servicios",
              name: "servicesDescription",
              widget: "text",
            }
          - label: "Subservicios"
            name: "subservices"
            widget: "list"
            fields:
              - { label: "Subservicio", name: "subservice", widget: "string" }
              - {
                  label: "Imagen del Servicio",
                  name: "serviceImage",
                  widget: "image",
                }
          - { label: "Título Misión", name: "missionTitle", widget: "string" }
          - {
              label: "Subtítulo Misión",
              name: "missionSubtitle",
              widget: "markdown",
            }
          - { label: "Tercer Título", name: "thirdTitle", widget: "string" }
          - { label: "Foto de Fondo", name: "backgroundPhoto", widget: "image" }
          - {
              label: "Título Testimonios",
              name: "testimonialsTitle",
              widget: "string",
            }
          - {
              label: "Subtítulo Testimonios",
              name: "testimonialsSubtitle",
              widget: "markdown",
            }
          - label: "Testimonios"
            name: "testimonials"
            widget: "list"
            fields:
              - {
                  label: "Imagen del Testimonio",
                  name: "testimonialImage",
                  widget: "image",
                }
              - {
                  label: "Nombre del Testimonio",
                  name: "testimonialName",
                  widget: "string",
                }
              - {
                  label: "Rol del Testimonio",
                  name: "testimonialRole",
                  widget: "string",
                }
              - {
                  label: "Texto del Testimonio",
                  name: "testimonialText",
                  widget: "text",
                }
          - {
              label: "Título CTA Principal",
              name: "mainCtaTitle",
              widget: "string",
            }
          - {
              label: "Subtítulo CTA Principal",
              name: "mainCtaSubtitle",
              widget: "markdown",
            }
          - {
              label: "Texto del Botón CTA Principal",
              name: "mainCtaButtonText",
              widget: "string",
            }
          - { label: "Foto Avatar", name: "avatarPhoto", widget: "image" }
          - {
              label: "Título Sesión Gratis",
              name: "freeSessionTitle",
              widget: "markdown",
            }
          - {
              label: "Subtítulo Sesión Gratis",
              name: "freeSessionSubtitle",
              widget: "string",
            }
          - {
              label: "Texto del Botón Sesión Gratis",
              name: "freeSessionButtonText",
              widget: "string",
            }
          - {
              label: "Enlace del Botón Sesión Gratis",
              name: "freeSessionButtonLink",
              widget: "string",
            }

      - name: "navigation_en"
        label: "Navigation (English)"
        file: "content/navigation_en.md"
        fields:
          - {
              label: "Header Button Text",
              name: "headerButtonText",
              widget: "string",
            }
          - label: "Pages"
            name: "pages"
            widget: "list"
            fields:
              - { label: "Page Title", name: "pageTitle", widget: "string" }
              - { label: "Page Link", name: "pageLink", widget: "string" }

      - name: "navigation_es"
        label: "Navigation (Spanish)"
        file: "content/navigation_es.md"
        fields:
          - {
              label: "Texto del Botón del Encabezado",
              name: "headerButtonText",
              widget: "string",
            }
          - label: "Páginas"
            name: "pages"
            widget: "list"
            fields:
              - {
                  label: "Título de la Página",
                  name: "pageTitle",
                  widget: "string",
                }
              - {
                  label: "Enlace de la Página",
                  name: "pageLink",
                  widget: "string",
                }

      - name: "footer_en"
        label: "Footer (English)"
        file: "content/footer_en.md"
        fields:
          - {
              label: "Developer Signature",
              name: "developerSignature",
              widget: "string",
            }

      - name: "footer_es"
        label: "Footer (Spanish)"
        file: "content/footer_es.md"
        fields:
          - {
              label: "Firma del Desarrollador",
              name: "developerSignature",
              widget: "string",
            }
